## 🎓 Nhà tài trợ

Dự án được hỗ trợ bởi:

- **Thầy Trà** – Giảng viên hướng dẫn
- **Trường Đại học Bách Khoa**, Khoa Xây Dựng
- **Nhóm Nghiên cứu Smart Twin BKU**

🙏 Xin cảm ơn sự đồng hành và tài trợ quý báu!
